### ISSUE TITLE
RESOURCE_EXHAUSTED: a single table row is larger than the maximum message size

### ISSUE THREAD

**Issue by akkomar** [GoogleCloudPlatform/spark-bigquery-connector#62] opened 2019-09-30 08:11 UTC
We're hitting the following error:
```
com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ResourceExhaustedException: 
com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: 
RESOURCE_EXHAUSTED: there was an error operating on {REDACTED}: a single table row is larger than the maximum message size
```

This might be a duplicate of https://github.com/GoogleCloudPlatform/spark-bigquery-connector/issues/22

**Comment by sauvala** [comment] 2019-10-29 12:06
I'm receiving this same error

**Comment by davidrabinowitz** [comment] 2019-10-29 16:24
Duplicate of #22

**Closed by davidrabinowitz** 2019-10-29 16:24 UTC
Labels: duplicate
