### ISSUE TITLE
Expand predicate filters

### ISSUE THREAD

**Issue by pmkc** [GoogleCloudPlatform/spark-bigquery-connector#4] opened 2019-03-04 23:31 UTC
This is blocked on the API limits at the moment.

**Comment by darrenhaken** [comment] 2019-04-10 21:47
Any idea for the timeline around this? Appetite for contributions?

**Comment by kmjung** [comment] 2019-04-10 21:52
The issue is on the server side, unfortunately, not in the connector. We're working on expanding push-down filtering further at the moment, but I don't have a specific ETA for you.

**Comment by darrenhaken** [comment] 2019-04-10 21:53
Ah that’s a shame. I guess the same applies for the date predicate GitHub issue too?

**Comment by kmjung** [comment] 2019-04-10 21:54
The date predicate issue may be a separate issue. I will take a look at that one as soon as I can -- it should be a simple repro, in theory -- but haven't had time to do so yet.

**Comment by kmjung** [comment] 2019-11-21 17:09
This was resolved by https://github.com/GoogleCloudPlatform/spark-bigquery-connector/pull/39.

**Closed by kmjung** 2019-11-21 17:09 UTC
